# Generated by Django 4.1.1 on 2022-10-03 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0003_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeorgeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thegame.question')),
            ],
        ),
        migrations.CreateModel(
            name='KelsyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thegame.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
