# Generated by Django 4.1.1 on 2022-10-03 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0004_georgeanswer_kelsyanswer_delete_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelsyanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegame.question'),
        ),
    ]
