# Generated by Django 4.1.1 on 2022-10-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0007_alter_georgeanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelsyanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='thegame.question'),
        ),
    ]
