# Generated by Django 4.1.2 on 2022-10-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0011_alter_room_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_num',
            new_name='room_number',
        ),
    ]
