# Generated by Django 4.1.2 on 2022-10-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0012_rename_room_num_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(max_length=5),
        ),
    ]
