# Generated by Django 4.1.2 on 2022-10-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0018_remove_room_user_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='room',
            field=models.ForeignKey(default=426, on_delete=django.db.models.deletion.CASCADE, to='thegame.room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
    ]
