# Generated by Django 4.1.2 on 2022-10-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0020_alter_question_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='room',
        ),
    ]
