# Generated by Django 4.1.2 on 2022-10-06 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thegame', '0022_question_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='person',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegame.room'),
        ),
    ]
