# Generated by Django 4.1.2 on 2022-10-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0022_question_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
