# Generated by Django 4.1.2 on 2022-10-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0023_remove_room_id_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thegame.room'),
        ),
    ]
