# Generated by Django 4.1.2 on 2022-10-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0025_room_history_one log or something'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='one answer per user'),
        ),
    ]
