# Generated by Django 4.1.2 on 2022-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0027_remove_answer_one answer per user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('user', 'answer', 'question'), name='one answer per user per question'),
        ),
    ]
