# Generated by Django 4.1.2 on 2022-10-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thegame', '0028_answer_one answer per user per question'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('room_number',), name='Keep room numbers unique'),
        ),
    ]
